# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
development:
  adapter: postgresql
  encoding: unicode
  database: messaging_api
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: messaging_api_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: messaging_api_production
  pool: 5
  username:
  password:
